server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:faq
  validationQuery: select 1
  checkConnectionWhileIdle: true
  properties:
    hibernate.hbm2ddl.auto: create
    hibernate.show_sql: true
    hibernate.format_sql: true
