server:
  type: default
  applicationConnectors:
    - type: http
      port: 8080

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:./db/faq
  validationQuery: select 1
  checkConnectionWhileIdle: true
  properties:
    hibernate.show_sql: true
    hibernate.format_sql: true
